# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsCli < Formula
  desc "CLI tool for managing Jenkins jobs from the command line"
  homepage "https://github.com/zgfh/jenkins-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zgfh/jenkins-cli/releases/download/v0.1.0/jenkins-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "c96779290fefa4dc9945f4c5d22f0261007695922d41f636849f665dddb8e47d"

      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zgfh/jenkins-cli/releases/download/v0.1.0/jenkins-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "342bb2d00b898d8987cf60a21e605b69328e3484bb712e0c7d58fc811d1fce31"

      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zgfh/jenkins-cli/releases/download/v0.1.0/jenkins-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "e837a353f8254a3116f3fa5b817b2b113f330e47379c388ef9883d1203349101"
      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zgfh/jenkins-cli/releases/download/v0.1.0/jenkins-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "2a6c0ce296ff240c43e5222fe6a96289e19facdae4352571bd3fab839faf54fe"
      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
  end

  test do
    system "#{bin}/jenkins-cli", "version"
  end
end
